---
- name: Install curl
  become: true
  ansible.builtin.apt:
    name: curl
    state: present
- name: Install Node Version Manager
  ansible.builtin.shell: >
    set -o pipefail && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
- name: Copy zsh nodejs config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nodejs.sh"
    dest: "$HOME/.zshrc.d/nodejs.sh"
    mode: 0644
- name: Install node
  ansible.builtin.shell: >
    . $HOME/.zshrc
    nvm install {{ node_version }}
    nvm use {{ node_version }}
  args:
    executable: /usr/bin/zsh
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/node/v{{ node_version }}"
- name: Install pnpm
  ansible.builtin.shell: >
    . $HOME/.zshrc
    npm install -g pnpm
  args:
    executable: /usr/bin/zsh
    chdir: "$HOME"
    creates: "$HOME/.nvm/versions/node/v{{ node_version }}/bin/pnpm"
