---
- name: Check if {{ path }} exists
  ansible.builtin.stat:
    path: "{{ path }}"
  register: dest
- name: Cloning {{ url }} to {{ path }}
  ansible.builtin.git:
    repo: "{{ url }}"
    dest: "{{ path }}"
    version: "HEAD"
  when: not dest.stat.exists
