---
- name: Install zsh and git
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - git
    state: present
- name: Set shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
- name: Install Oh-My-Zsh
  ansible.builtin.include_tasks:
    file: clone.yml
    apply:
      vars:
        url: https://github.com/robbyrussell/oh-my-zsh
        path: $HOME/.oh-my-zsh
        version: "HEAD"
- name: Install zsh plugins
  ansible.builtin.include_tasks:
    file: clone.yml
    apply:
      vars:
        url: https://github.com/zsh-users/{{ item }}
        path: $HOME/.oh-my-zsh/custom/plugins/{{ item }}
        version: "HEAD"
  with_items:
    - zsh-completions
    - zsh-autosuggestions
    - zsh-syntax-highlighting
- name: Install Spaceship
  ansible.builtin.include_tasks:
    file: clone.yml
    apply:
      vars:
        url: https://github.com/spaceship-prompt/spaceship-prompt
        path: $HOME/.oh-my-zsh/custom/themes/spaceship-prompt
        version: "HEAD"
- name: Symlink Spaceship
  ansible.builtin.file:
    src: $HOME/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme
    dest: $HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    state: link
- name: Copy zshrc
  ansible.builtin.template:
    src: zshrc
    dest: $HOME/.zshrc
    mode: 0644
- name: Create .zshrc.d directory
  ansible.builtin.file:
    path: $HOME/.zshrc.d
    state: directory
    mode: 0755
