- name: install i3 gaps and feh
  community.general.pacman:
    name:
      - i3-gaps
      - feh
    state: present
- name: copy config file
  ansible.builtin.copy:
    src: config
    dest: ~/.config/i3/
- name: copy unsplash-wallpaper.sh file
  ansible.builtin.copy:
    src: unsplash-wallpaper.sh
    dest: ~/.config/i3/
    mode: u=rwx,g=rx,o=rx
