galaxy_info:
  author: Sylvain VISTE
  description: Installs my dotfile configurations
  license: MIT
  min_ansible_version: 2.1

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: ArchLinux
      versions:
        - all

  galaxy_tags: []

dependencies: []
